<script setup>
import { Head,Link,usePage } from '@inertiajs/vue3'; import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import PageHeader from '@/Components/UI/PageHeader.vue'; import StatusBadge from '@/Components/UI/StatusBadge.vue'; import PriorityBadge from '@/Components/UI/PriorityBadge.vue'; import EmptyState from '@/Components/UI/EmptyState.vue'; import ConfirmDeleteModal from '@/Components/UI/ConfirmDeleteModal.vue';
defineProps({website:Object}); const user=usePage().props.auth.user; const fullDate=v=>v?new Intl.DateTimeFormat('es-ES',{dateStyle:'medium'}).format(new Date(v)):'No indicado';
</script>
<template><Head :title="website.name"/><AuthenticatedLayout title="Detalle web"><PageHeader eyebrow="Web gestionada" :title="website.name" :description="website.client.company_name" :back-href="route('websites.index')"><a :href="website.url" target="_blank" rel="noopener" class="btn-secondary">Abrir web ↗</a><Link v-if="user.role==='admin'" :href="route('websites.edit',website.id)" class="btn-primary">Editar</Link><ConfirmDeleteModal v-if="user.role==='admin'" :url="route('websites.destroy',website.id)" message="Solo se eliminará si no existen tickets ni tareas asociadas."/></PageHeader>
<div class="grid gap-6 xl:grid-cols-[1fr_340px]"><div class="space-y-6"><section class="panel"><div class="flex justify-between border-b border-slate-100 p-5"><h3 class="font-bold">Tickets asociados</h3><Link :href="route('tickets.create',{website_id:website.id})" class="text-sm font-semibold text-indigo-600">Nuevo ticket →</Link></div><div v-if="website.tickets.length" class="divide-y divide-slate-100"><Link v-for="ticket in website.tickets" :key="ticket.id" :href="route('tickets.show',ticket.id)" class="flex flex-col gap-2 p-4 hover:bg-slate-50 sm:flex-row sm:items-center"><div class="flex-1"><p class="text-sm font-semibold">#{{ticket.id}} · {{ticket.title}}</p><p class="text-xs text-slate-500">{{ticket.assignee?.name||'Sin asignar'}}</p></div><div class="flex gap-2"><PriorityBadge :priority="ticket.priority"/><StatusBadge :status="ticket.status"/></div></Link></div><EmptyState v-else title="Sin tickets asociados"/></section>
<section class="panel"><div class="flex justify-between border-b border-slate-100 p-5"><h3 class="font-bold">Mantenimiento</h3><Link v-if="user.role==='admin'" :href="route('maintenance.create',{website_id:website.id})" class="text-sm font-semibold text-indigo-600">Nueva tarea →</Link></div><div v-if="website.maintenance_tasks.length" class="divide-y divide-slate-100"><Link v-for="task in website.maintenance_tasks" :key="task.id" :href="route('maintenance.show',task.id)" class="flex items-center gap-3 p-4 hover:bg-slate-50"><div class="flex-1"><p class="text-sm font-semibold">{{task.title}}</p><p class="text-xs text-slate-500">{{task.category}} · {{fullDate(task.scheduled_at)}}</p></div><StatusBadge :status="task.status"/></Link></div><EmptyState v-else title="Sin tareas programadas"/></section></div>
<aside class="space-y-6"><section class="panel p-5"><div class="flex justify-between"><h3 class="font-bold">Estado técnico</h3><StatusBadge :status="website.status"/></div><dl class="mt-5 grid gap-4 text-sm"><div><dt class="text-xs font-bold uppercase text-slate-400">URL</dt><dd class="mt-1 break-all font-medium text-indigo-600">{{website.url}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Tecnología</dt><dd class="mt-1">{{website.technology}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Plan</dt><dd class="mt-1 capitalize">{{website.maintenance_plan}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Hosting</dt><dd class="mt-1">{{website.hosting_provider||'No indicado'}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">SSL</dt><dd class="mt-1"><StatusBadge :status="website.ssl_status"/></dd></div></dl></section><section class="panel p-5"><h3 class="font-bold">Vencimientos</h3><div class="mt-4 grid grid-cols-2 gap-3"><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Dominio</p><p class="mt-1 text-sm font-bold">{{fullDate(website.domain_expires_at)}}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-xs text-slate-400">Hosting</p><p class="mt-1 text-sm font-bold">{{fullDate(website.hosting_expires_at)}}</p></div></div></section><section class="panel p-5"><h3 class="font-bold">Notas</h3><p class="mt-3 whitespace-pre-line text-sm text-slate-600">{{website.notes||'Sin notas técnicas.'}}</p></section></aside></div>
</AuthenticatedLayout></template>
